name: CI
on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.0, 1.1, 1.2, 1.3, 1.4]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
          arch: x64
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
      - uses: codecov/codecov-action@v1
        if: ${{ matrix.julia-version == '1.4' && matrix.os =='ubuntu-latest' }}
